#Question 1
people = ['Ali', 'Muhammad', 'Rabi']
print("You are invited to my dinner, " + people[0] + ".")
print("You are invited to my dinner, " + people[1] + ".")
print("You are invited to my dinner, " + people[2] + ".")
x = people.pop(1)
print(x, "can't make it to the dinner.")
people.append('Abdullah')
print(people[2], "will be coming to the dinner instead of " + x + ".")
people.insert(0, 'Haashir')
people.insert(3, 'Farez')
people.insert(5, 'Fawaz')
print("You are invited to my dinner, " + people[0] + ".")
print("You are invited to my dinner, " + people[1] + ".")
print("You are invited to my dinner, " + people[2] + ".")
print("You are invited to my dinner, " + people[3] + ".")
print("You are invited to my dinner, " + people[4] + ".")
print("You are invited to my dinner, " + people[5] + ".")

#Question 3
print("Sorry for the inconvenience", people, "but I will only be able to invite 2 people over for dinner.")
x = people.pop()
print("Sorry", x, 'I cannot invite you over for dinner today.')
x = people.pop()
print("Sorry", x, 'I cannot invite you over for dinner today.')
x = people.pop()
print("Sorry", x, 'I cannot invite you over for dinner today.')
x = people.pop()
print("Sorry", x, 'I cannot invite you over for dinner today.')
print("You are still invited for dinner " + people[0] + ".")
print("You are still invited for dinner " + people[1] + ".")
del(people)
print(people)